name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Nodejs Environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      - name: Run unit test
        run: pnpm test

      - name: Type check
        run: pnpm typecheck

      - name: Build the app
        run: pnpm build

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Nodejs Environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Build the app
        run: pnpm build
      - name: Apply Cloudflare Pages Config
        run: cp cloudflare/* dist/
      - name: Deploy Site on Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }} --commit-hash=${{ github.sha }} --branch=${{ github.ref_name }} --commit-dirty=true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
